### ISSUE TITLE
Add instructions on Docker

### ISSUE THREAD

**Issue by dotasek** [cytoscape/cytoscape-manual#37]
The Cytoscape Automation page should include information on Docker.

Some relevant pages from the old CyREST Wiki with good documentation as well as links to code using Cytoscape Automation and Docker:

https://github.com/cytoscape/cyREST/wiki/Docker-and-Data-Visualization
https://github.com/cytoscape/cyREST/wiki/Reproducible-workflows-with-Docker

**Comment by AlexanderPico** [comment]
Will do this when we have a solid Docker use case to document.
