### ISSUE TITLE
Broken link for XGMML specification

### ISSUE THREAD

**Issue by peterjc** [cytoscape/cytoscape-manual#45]
http://manual.cytoscape.org/en/3.7.2/Supported_Network_File_Formats.html has the following URL for the XGMML specification:

http://cgi5.cs.rpi.edu/research/groups/pb/punin/public_html/XGMML/

This link is dead. https://en.wikipedia.org/wiki/XGMML also lists the URL, noting it is broken.

**Comment by peterjc** [comment]
Should we just use archive.org or has the specification moved elsewhere?

https://web.archive.org/web/20140328030415/http://cgi5.cs.rpi.edu/research/groups/pb/punin/public_html/XGMML/

**Comment by AlexanderPico** [comment]
Let's swap it for https://en.wikipedia.org/wiki/XGMML

**Comment by khanspers** [comment]
replaced link with Wikipedia link: https://en.wikipedia.org/wiki/XGMML

**Comment by peterjc** [comment]
I have put the archive link on the wikipedia page.
