### ISSUE TITLE
Broken link for Graph Markup Language (GML) specification

### ISSUE THREAD

**Issue by peterjc** [cytoscape/cytoscape-manual#46]
http://manual.cytoscape.org/en/3.7.2/Supported_Network_File_Formats.html#gml-format says

> The GML file format specification is available at:
>
> http://www.infosun.fmi.uni-passau.de/Graphlet/GML/

This URL is dead. The wikipedia page might be a partial substitute? https://en.wikipedia.org/wiki/Graph_Modelling_Language

**Comment by khanspers** [comment]
URL has been updated in source

**Comment by peterjc** [comment]
Thank you.

Just to note, the new link is https://www.fim.uni-passau.de/fileadmin/files/lehrstuhl/brandenburg/projekte/gml/gml-technical-report.pdf
