### ISSUE TITLE
Degree Filters - definition needed

### ISSUE THREAD

**Issue by Althalis** [cytoscape/cytoscape-manual#47]
Dear contributors, 
I'm new to cytoscape and trying to manage my selection filters.
http://manual.cytoscape.org/en/3.7.2/Finding_and_Filtering_Nodes_and_Edges.html#filters

I sense that the Degree filter is interesting, but it's totally obscure to me what you mean by "degree". Can't figure out by playing with it.
Could this be defined in the documentation?

Also, when we talk about "distance", I guessed it was 1 edge = 1 distance unit, but I'm not even sure.

It might be trivial for people using the software all the time.
Thanks for the clarification :)
Best
Julie

**Comment by khanspers** [comment]
Hi Julie,
Degree refers to the number of edges connecting to the node. As for distance between two nodes, it is the number of edges connecting them in the shortest path between them. I will add a better description for this in the next update to the manual.
