### ISSUE TITLE
Manually creating directed edges

### ISSUE THREAD

**Issue by bramson** [cytoscape/cytoscape-manual#48]
I want to manually create various network diagrams that include directed edges; for example, planning Bayesian networks and graph database schema.  Cytoscape seems to support most of what is needed to do that, but I don't see anyway to manually create a directed edge between two nodes.

I can easily create an undirected link between two (or among n) nodes, or create an undirected edge from a specific node to a specific node.  But I can't find any option to make this edge directed...which is intuitively the default action when I am specifying the from and two nodes rather creating a edges between/among selected nodes.  Perhaps this functionality exists in the software as a preference/option, but I can't find it.

So, if this capability exists, then please add directions for manually creating directed edges to the documentation section on creating networks.  Also, I would recommend creating a item on the right-click drop-down menu for "Add > Directed Edge".

If manually creating directed edges is not supported, then please add this basic functionality.  I mean, so many networks are directed that not supporting them really undercuts the value of this otherwise impressive tool.

**Comment by khanspers** [comment]
Hi @bramson,
I don't think there is a way to manually create a directed edge. Please send an email to cytoscape-helpdesk@googlegroups.com to request adding this as a feature.
