### ISSUE TITLE
how to prevent edge reshaping upon zoom?

### ISSUE THREAD

**Issue by manihamidi** [cytoscape/cytoscape-manual#50]
Zooming in/out changes which edges are shown and _how_ they are drawn... is there any way to keep both of these fixed so they are not affected by zooming? 

e.g, see below where I'm using a yFiles hierarchic layout on a directed network, as I zoom out the edges switch to being drawn as straight lines instead of nicely bent ones:

![Peek 2020-08-27 13-17](https://user-images.githubusercontent.com/15459064/91490691-b4c05300-e867-11ea-8b73-72283acc1aca.gif)

Some edges appear/disappear in addition to changing shape: but this is less frustrating as it seems to depend on whether their flanking nodes are in the view or not. However, if there's a way to change this behavior too, it'd be great to know!

Thanks!

```
System info: 
Ubuntu 18.04.5

Version: 3.8.0 
Java: 11.0.8 by Ubuntu
Java Home: /usr/lib/jvm/java-11-openjdk-amd64 
OS: Linux 5.4.0-42-generic - amd64
```

**Comment by khanspers** [comment]
Hi, I think what you're seeing has to do with the rendering engine lowering the level of detail while zooming, and there is no way around it. However, I would recommend posting this question as a bug to get clarification: https://cytoscape.org/bug-report.html.

**Comment by manihamidi** [comment]
thanks for the quick reply... yes I actually _just_ reported it there too... 

Hope there'll be work around eventually...

**Comment by manihamidi** [comment]
There is actually a button for this! 

![image](https://user-images.githubusercontent.com/15459064/91766066-d2a2f600-eb8e-11ea-9ff7-57c70102617f.png)


![image](https://user-images.githubusercontent.com/15459064/91766044-c880f780-eb8e-11ea-954e-214954ad2bf2.png)

Click the left most button on the bottom-right of the view, to "Always Show Graphics Details". 

This prevents the bends in the edges from being redrawn as straight lines upon zooming out. 

Closing the issue.
