### ISSUE TITLE
Chinese Version Cytoscape User Manual

### ISSUE THREAD

**Issue by leovan** [cytoscape/cytoscape-manual#53]
I maintain a Chinese version Cytoscape user manual at https://github.com/leovan/cytoscape-manual from version 3.8.2. Also I update to 3.9.0 based on the original English version. I use MkDoc rather than Sphinx to build the doc, so I think it'a unable to merge into this repository. I deploy the Chinese version on https://cytoscape.leovan.tech/. I wonder if there will a chance to add a link on the official Cytoscape user manual website to my Chinese version? I think it may help people who use Chinese make it easy to use the Cytoscape App. And if you need change or update something in my Chinese version repository, please let me know.

**Comment by khanspers** [comment]
Hi Leo, thank you for creating the Chinese version of the Cytoscape manual! To answer your question, yes, we would like to link to it from the official manual, probably with a sentence towards the top of the landing page, something like "Available in Chinese: https://cytoscape.leovan.tech/“." 
I will add it to the list for the next update.

**Comment by leovan** [comment]
Cool, hope this Chinese version help users some.

**Comment by khanspers** [comment]
Hi Leo, we can also setup a weblink to the Chinese version of the manual, for example manual-cn.cytoscape.org. It would point to https://cytoscape.leovan.tech/, so this URL would need to be stable. Would that work?

**Comment by leovan** [comment]
Thanks for you reply. The website is stable, I deploy it with Cloudflare pages. The original domain for this manual is https://cytoscape-manual.pages.dev, I think let manual-cn.cytoscape.org be a CNAME of cytoscape-manual.pages.dev is better. Unfortunately, I lost my 2-factor code to log into Cloudflare account because I change a new phone. I already sent my request to reset, the response said it would take 3-5 days to make it work. I think manual-cn.cytoscape.org will be more reliable for users. I will let you know once I add manual-cn.cytoscape.org as a CNAME.

**Comment by khanspers** [comment]
Hi Leo, Actually the CNAME is an attribute of Cytoscape.org, so the mapping has to happen on our end. It's not a problem at all. To confirm, this is the URL to map to that won't change: "https://cytoscape-manual.pages.dev"

**Comment by leovan** [comment]
The URL https://cytoscape-manual.pages.dev won't change. Yes, CNAME will be set on your side, yet I am not sure whether do I need to add manual-cn.cytoscape.org as a custom URL for this site in Cloudflare or not. Let's try to set manual-cn.cytoscape.org as CNAME of cytoscape-manual.pages.dev to check if it works or not.

**Comment by leovan** [comment]
Hi @khanspers , I have added manual-cn.cytoscape.org as a custom domain for cytoscape-manual.pages.dev on cloudflare. I think after you set it as a CNAME of cytoscape-manual.pages.dev, it will work.

**Comment by khanspers** [comment]
Thanks Leo. I'll let you know when I have an update. You can also email me directly at kristina.hanspers@gladstone.ucsf.edu.
