### ISSUE TITLE
font size of cytoscape 3.10 in ubuntu 23.04 

### ISSUE THREAD

**Issue by shamshad-ather** [cytoscape/cytoscape-manual#67]
![image](https://github.com/cytoscape/cytoscape-manual/assets/111559530/c5375c91-9eb1-40ab-a9d2-f3e72ae5b21d)

How do i fix it.

**Comment by khanspers** [comment]
Hi @shamshad-ather. Please post your question to cytoscape-helpdesk@googlegroups.com.

**Comment by shamshad-ather** [comment]
Thank You
