### ISSUE TITLE
Fix broken version selector in ReadTheDocs

### ISSUE THREAD

**Issue by khanspers** [cytoscape/cytoscape-manual#70]
The lower-left version selector drop-down doesn't work on 'latest': https://manual.cytoscape.org/en/latest

Not sure why but could have something to do with the 'sphinx_rtd_theme'. 

Note: The selector works fine on stable and 3.10.1 versions (which is what we link to from website and UI), since these were built before the latest set of changes that introduced this bug.

**Comment by bdemchak** [comment]
Does not seem to happen on py4cytoscape documents ... either [latest ](https://py4cytoscape.readthedocs.io/en/latest/)or [1.9.0](https://py4cytoscape.readthedocs.io/en/1.9.0/)

**Comment by khanspers** [comment]
There was a jQuery error in the browser console; found this https://github.com/readthedocs/sphinx_rtd_theme/issues/1452.

Adding extensions = ["sphinxcontrib.jquery"] solves the problem.

**Comment by bdemchak** [comment]
I see ... I think the difference is that the requirements.txt file for py4cytoscape specifies a specific sphinx version that didn't have this problem:

sphinx==3.5.4
jinja2==3.0.3
pandas
networkx
requests
colorbrewer
chardet
igraph
sphinx_autodoc_typehints
sphinx_rtd_theme
ipykernel
decorator
backoff
colour

Thanks for posting your solution.
