### ISSUE TITLE
The Quick Tour link in page 2 seems to not exist anymore

### ISSUE THREAD

**Issue by ooker777** [cytoscape/cytoscape-manual#72]
The link https://manual.cytoscape.org/en/stable/Launching_Cytoscape.html#Quick_Tour_of_Cytoscape.html#quick-tour-of-cytoscape in this section:

![](https://i.imgur.com/0cRBExL.png)

seems to be removed.

**Comment by khanspers** [comment]
Fixed. Thanks for reporting!
