### ISSUE TITLE
ClusteringCoefficient vs ClosenessCentrality

### ISSUE THREAD

**Issue by marina-vn** [cytoscape/cytoscape-manual#73]
Hi,

I'm studying a network of genomes recovered by different methodologies, and I want to compare which methodology is capable of recovering more "singletons" or genomes less connected to the rest. I was considering the attributes Clustering Coefficient and Closeness Centrality, as I understand they are related to this question, but when analyzing Clustering Coefficient, I find that one of the methods has the highest values while the same method has lower Closeness Centrality values than others...

What would be the best way of analyzing this?
Thanks in advance,

**Comment by khanspers** [comment]
Hi @marina-vn, thanks for your question. This repo is for building and maintaining the Cytoscape manual. The best place for for questions about using Cytoscape is the Cytoscape Helpdesk google group: https://groups.google.com/g/cytoscape-helpdesk
